language: python
python:
  - "3.6"

addons:
    apt:
        packages:
            - portaudio19-dev

# command to install dependencies
install: "pip install -r gatekeeper/requirements.txt"

# command to run tests
script: python -m compileall gatekeeper/
